export const ALL_RESTAURANT_REQUEST =  "ALL_RESTAURANT_REQUEST";
export const ALL_RESTAURANT_SUCCESS =  "ALL_RESTAURANT_SUCCESS";
export const ALL_RESTAURANT_FAIL =  "ALL_RESTAURANT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS"

export const SORT_BY_RATINGS = "SORT_BY_RATINGS"
export const SORT_BY_REVIEWS = "SORT_BY_REVIEWS"
export const TOGGLE_VEG_ONLY = "TOGGLE_VEG_ONLY"
